# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        App\Entity\User:
            algorithm: sha512
            encode_as_base64: true
            iterations: 5

    providers:
        my_provider:
            entity:
                class: App\Entity\User
                property: login

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: /proxy
            logout:
                path:   /logout
                target: /login

    access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/user/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }